
"use strict"
/*****************

Abysmal Internet Search
Percy Dragon

I'm going to start off slow by having a random generated title for click bait articles
than I might use tracey to have randomly generated text accompony it.

My end idea is to have it look like google, with clickbait articles at the top of the SEO. That may,
however, be too ambitious. But yolo.

******************/
let videoHostingSites = [
      "AcFun",
      "AfreecaTV",
      "Archive.org",
      "Bilibili",
      "Blip.tv",
      "BlogTV",
      "Break.com",
      "Brightcove",
      "Buzznet",
      "Cambridge Imaging",
      "Comedy.com",
      "Commons.wikimedia.org",
      "Crackle",
      "DaCast",
      "Dailymotion Cloud",
      "Dailymotion",
      "EngageMedia",
      "ExpoTV",
      "Facebook",
      "Flickr",
      "Fotki",
      "Frequency",
      "Funnyordie.com",
      "Funshion",
      "GNU MediaGoblin",
      "GodTube",
      "HD share",
      "Hulu",
      "islamictube",
      "Kaltura",
      "Kewego",
      "Lafango",
      "LeTV",
      "Liveleak",
      "MainStreaming",
      "MediaCore",
      "Mefeedia",
      "Metacafe",
      "MetaCDN",
      "Mevio",
      "MUZU.TV",
      "Myspace",
      "MyVideo",
      "Nico Nico Douga",
      "OneWorldTV",
      "Ooyala",
      "Openfilm",
      "Ora TV",
      "Panopto",
      "Photobucket",
      "Pixorial",
      "Plumi",
      "Pornhub",
      "QQ Video",
      "Rediff",
      "RedTube",
      "RuTube",
      "Sapo Videos",
      "SchoolTube",
      "ScienceStage",
      "Sevenload",
      "SmugMug",
      "Synaptop",
      "Tape.tv",
      "thePlatform",
      "Trilulilu",
      "TroopTube",
      "Tudou",
      "Tune.pk",
      "TV UOL",
      "Ustream",
      "Vbox7",
      "Veoh",
      "ViaStreaming",
      "Viddler",
      "Viddsee",
      "Videojug",
      "Videolog",
      "Vidoosh",
      "Vidyard",
      "Vimeo",
      "VK",
      "Vuze",
      "Vzaar",
      "Wildscreen.tv",
      "Wistia",
      "xHamster",
      "Xtube",
      "XVideos",
      "Yahoo! Video",
      "Youku",
      "YouPorn",
      "YouTube"
    ];

let artIsms = [
"abstract expressionism",
"academic",
"action painting",
"aestheticism",
"art deco",
"art nouveau",
"avant-garde",
"barbizon school",
"baroque",
"bauhaus",
"biedermeier",
"caravaggisti",
"carolingian",
"classicism",
"cloisonnism",
"cobra",
"color field painting",
"conceptual art",
"cubism",
"cubo-futurism",
"dada",
"dadaism",
"de stijl",
"deformalism",
"der blaue reiter",
"die brücke",
"divisionism",
"eclecticism",
"ego-futurism",
"existentialism",
"expressionism",
"fauvism",
"fluxus",
"formalism",
"futurism",
"geometric abstraction",
"gothic art",
"gründerzeit",
"hard-edge painting",
"historicism",
"hudson river school",
"humanism",
"hyperrealism",
"idealism",
"illusionism",
"immagine&poesia",
"impressionism",
"incoherents",
"installation art",
"international gothic",
"intervention art",
"jugendstil",
"kinetic art",
"land art",
"les nabis",
"lettrism",
"lowbrow",
"luminism",
"lyrical abstraction",
"mail art",
"manierism",
"mannerism",
"maximalism",
"merovingian",
"metaphysical art ",
"minimalism",
"modern art",
"modernism",
"monumentalism",
"multiculturalism",
"naturalism",
"neo-classicism",
"neo-dada",
"neo-expressionism",
"neo-fauvism",
"neo-geo",
"neo-impressionism",
"neo-minimalism",
"neoclassicism",
"neoism",
"neue slowenische kunst",
"new media art",
"new objectivity",
"nonconformism",
"nouveau realisme",
"op art",
"orphism",
"ottonian",
"outsider art",
"performance art",
"perspectivism",
"photorealism",
"pointilism",
"pop art",
"post-conceptualism",
"post-impressionism",
"post-minimalism",
"post-painterly abstraction",
"post-structuralism",
"postminimalism",
"postmodern art",
"postmodernism",
"pre-raphaelites",
"precisionism",
"primitivism",
"purism",
"rayonism",
"realism",
"relational art",
"remodernism",
"renaissance",
"rococo",
"romanesque",
"romanticism",
"russian futurism",
"russian symbolism",
"scuola romana",
"secularism",
"situationist international",
"social realism",
"socialist realism",
"sound art",
"street art",
"structuralism",
"stuckism international",
"stuckism",
"superflat",
"superstroke",
"suprematism",
"surrealism",
"symbolism",
"synchromism",
"synthetism",
"systems art",
"tachism",
"tachisme",
"tonalism",
"video art",
"video game art",
"vorticism",
"young british artists"
];

let adjs = [
  "Aristotelian",
      "Arthurian",
      "Bohemian",
      "Brethren",
      "Mosaic",
      "Oceanic",
      "Proctor",
      "Terran",
      "Tudor",
      "abroad",
      "absorbing",
      "abstract",
      "academic",
      "accelerated",
      "accented",
      "accountant",
      "acquainted",
      "acute",
      "addicting",
      "addictive",
      "adjustable",
      "admired",
      "adult",
      "adverse",
      "advised",
      "aerosol",
      "afraid",
      "aggravated",
      "aggressive",
      "agreeable",
      "alienate",
      "aligned",
      "all-round",
      "alleged",
      "almond",
      "alright",
      "altruistic",
      "ambient",
      "ambivalent",
      "amiable",
      "amino",
      "amorphous",
      "amused",
      "anatomical",
      "ancestral",
      "angelic",
      "angrier",
      "answerable",
      "antiquarian",
      "antiretroviral",
      "appellate",
      "applicable",
      "apportioned",
      "approachable",
      "appropriated",
      "archer",
      "aroused",
      "arrested",
      "assertive",
      "assigned",
      "athletic",
      "atrocious",
      "attained",
      "authoritarian",
      "autobiographical",
      "avaricious",
      "avocado",
      "awake",
      "awsome",
      "backstage",
      "backwoods",
      "balding",
      "bandaged",
      "banded",
      "banned",
      "barreled",
      "battle",
      "beaten",
      "begotten",
      "beguiled",
      "bellied",
      "belted",
      "beneficent",
      "besieged",
      "betting",
      "big-money",
      "biggest",
      "biochemical",
      "bipolar",
      "blackened",
      "blame",
      "blessed",
      "blindfolded",
      "bloat",
      "blocked",
      "blooded",
      "blue-collar",
      "blushing",
      "boastful",
      "bolder",
      "bolstered",
      "bonnie",
      "bored",
      "boundary",
      "bounded",
      "bounding",
      "branched",
      "brawling",
      "brazen",
      "breeding",
      "bridged",
      "brimming",
      "brimstone",
      "broadest",
      "broiled",
      "broker",
      "bronze",
      "bruising",
      "buffy",
      "bullied",
      "bungling",
      "burial",
      "buttery",
      "candied",
      "canonical",
      "cantankerous",
      "cardinal",
      "carefree",
      "caretaker",
      "casual",
      "cathartic",
      "causal",
      "chapel",
      "characterized",
      "charcoal",
      "cheeky",
      "cherished",
      "chipotle",
      "chirping",
      "chivalrous",
      "circumstantial",
      "civic",
      "civil",
      "civilised",
      "clanking",
      "clapping",
      "claptrap",
      "classless",
      "cleansed",
      "cleric",
      "cloistered",
      "codified",
      "colloquial",
      "colour",
      "combat",
      "combined",
      "comely",
      "commissioned",
      "commonplace",
      "commuter",
      "commuting",
      "comparable",
      "complementary",
      "compromising",
      "conceding",
      "concentrated",
      "conceptual",
      "conditioned",
      "confederate",
      "confident",
      "confidential",
      "confining",
      "confuse",
      "congressional",
      "consequential",
      "conservative",
      "constituent",
      "contaminated",
      "contemporaneous",
      "contraceptive",
      "convertible",
      "convex",
      "cooked",
      "coronary",
      "corporatist",
      "correlated",
      "corroborated",
      "cosmic",
      "cover",
      "crash",
      "crypto",
      "culminate",
      "cushioned",
      "dandy",
      "dashing",
      "dazzled",
      "decreased",
      "decrepit",
      "dedicated",
      "defaced",
      "defective",
      "defenseless",
      "deluded",
      "deodorant",
      "departed",
      "depress",
      "designing",
      "despairing",
      "destitute",
      "detective",
      "determined",
      "devastating",
      "deviant",
      "devilish",
      "devoted",
      "diagonal",
      "dictated",
      "didactic",
      "differentiated",
      "diffused",
      "dirtier",
      "disabling",
      "disconnected",
      "discovered",
      "disdainful",
      "diseased",
      "disfigured",
      "disheartened",
      "disheveled",
      "disillusioned",
      "disparate",
      "dissident",
      "doable",
      "doctrinal",
      "doing",
      "dotted",
      "double-blind",
      "downbeat",
      "dozen",
      "draining",
      "draught",
      "dread",
      "dried",
      "dropped",
      "dulled",
      "duplicate",
      "eaten",
      "echoing",
      "economical",
      "elaborated",
      "elastic",
      "elective",
      "electoral",
      "elven",
      "embryo",
      "emerald",
      "emergency",
      "emissary",
      "emotional",
      "employed",
      "enamel",
      "encased",
      "encrusted",
      "endangered",
      "engraved",
      "engrossing",
      "enlarged",
      "enlisted",
      "enlivened",
      "ensconced",
      "entangled",
      "enthralling",
      "entire",
      "envious",
      "eradicated",
      "eroded",
      "esoteric",
      "essential",
      "evaporated",
      "ever-present",
      "evergreen",
      "everlasting",
      "exacting",
      "exasperated",
      "excess",
      "exciting",
      "executable",
      "existent",
      "exonerated",
      "exorbitant",
      "exponential",
      "export",
      "extraordinary",
      "exultant",
      "exulting",
      "facsimile",
      "fading",
      "fainter",
      "faith-based",
      "fallacious",
      "faltering",
      "famous",
      "fancier",
      "fast-growing",
      "fated",
      "favourable",
      "fearless",
      "feathered",
      "fellow",
      "fermented",
      "ferocious",
      "fiddling",
      "filling",
      "firmer",
      "fitted",
      "flammable",
      "flawed",
      "fledgling",
      "fleshy",
      "flexible",
      "flickering",
      "floral",
      "flowering",
      "flowing",
      "foggy",
      "folic",
      "foolhardy",
      "foolish",
      "footy",
      "forehand",
      "forked",
      "formative",
      "formulaic",
      "foul-mouthed",
      "fractional",
      "fragrant",
      "fraudulent",
      "freakish",
      "freckled",
      "freelance",
      "freight",
      "fresh",
      "fretted",
      "frugal",
      "fulfilling",
      "fuming",
      "funded",
      "funny",
      "garbled",
      "gathered",
      "geologic",
      "geometric",
      "gibberish",
      "gilded",
      "ginger",
      "glare",
      "glaring",
      "gleaming",
      "glorified",
      "glorious",
      "goalless",
      "gold-plated",
      "goody",
      "grammatical",
      "grande",
      "grateful",
      "gratuitous",
      "graven",
      "greener",
      "grinding",
      "grizzly",
      "groaning",
      "grudging",
      "guaranteed",
      "gusty",
      "half-breed",
      "hand-held",
      "handheld",
      "hands-off",
      "hard-pressed",
      "harlot",
      "healing",
      "healthier",
      "healthiest",
      "heart",
      "heart-shaped",
      "heathen",
      "hedonistic",
      "heralded",
      "herbal",
      "high-density",
      "high-performance",
      "high-res",
      "high-yield",
      "hissy",
      "hitless",
      "holiness",
      "homesick",
      "honorable",
      "hooded",
      "hopeless",
      "horrendous",
      "horrible",
      "hot-button",
      "huddled",
      "human",
      "humbling",
      "humid",
      "humiliating",
      "hypnotized",
      "idealistic",
      "idiosyncratic",
      "ignited",
      "illustrated",
      "illustrative",
      "imitated",
      "immense",
      "immersive",
      "immigrant",
      "immoral",
      "impassive",
      "impressionable",
      "improbable",
      "impulsive",
      "in-between",
      "in-flight",
      "inattentive",
      "inbound",
      "inbounds",
      "incalculable",
      "incomprehensible",
      "indefatigable",
      "indigo",
      "indiscriminate",
      "indomitable",
      "inert",
      "inflate",
      "inform",
      "inheriting",
      "injured",
      "injurious",
      "inking",
      "inoffensive",
      "insane",
      "insensible",
      "insidious",
      "insincere",
      "insistent",
      "insolent",
      "insufferable",
      "intemperate",
      "interdependent",
      "interesting",
      "interfering",
      "intern",
      "interpreted",
      "intersecting",
      "intolerable",
      "intolerant",
      "intuitive",
      "irresolute",
      "irritate",
      "jealous",
      "jerking",
      "joining",
      "joint",
      "journalistic",
      "joyful",
      "keyed",
      "knowing",
      "lacklustre",
      "laden",
      "lagging",
      "lamented",
      "laughable",
      "layered",
      "leather",
      "leathern",
      "leery",
      "left-footed",
      "legible",
      "leisure",
      "lessening",
      "liberating",
      "life-size",
      "lifted",
      "lightest",
      "limitless",
      "listening",
      "literary",
      "liver",
      "livid",
      "lobster",
      "locked",
      "long-held",
      "long-lasting",
      "long-running",
      "long-suffering",
      "loudest",
      "loveliest",
      "low-budget",
      "low-carb",
      "lowering",
      "lucid",
      "luckless",
      "lusty",
      "luxurious",
      "magazine",
      "maniac",
      "manmade",
      "maroon",
      "mastered",
      "mated",
      "material",
      "materialistic",
      "meaningful",
      "measuring",
      "mediaeval",
      "medical",
      "meditated",
      "medley",
      "melodic",
      "memorable",
      "memorial",
      "metabolic",
      "metallic",
      "metallurgical",
      "metering",
      "midair",
      "midterm",
      "midway",
      "mighty",
      "migrating",
      "mind-blowing",
      "mind-boggling",
      "minor",
      "mirrored",
      "misguided",
      "misshapen",
      "mitigated",
      "mixed",
      "modernized",
      "molecular",
      "monarch",
      "monastic",
      "morbid",
      "motley",
      "motorized",
      "mounted",
      "multi-million",
      "multidisciplinary",
      "muscled",
      "muscular",
      "muted",
      "mysterious",
      "mythic",
      "nail-biting",
      "natural",
      "nauseous",
      "negative",
      "networked",
      "neurological",
      "neutered",
      "newest",
      "night",
      "nitrous",
      "no-fly",
      "noncommercial",
      "nonsense",
      "north",
      "nuanced",
      "occurring",
      "offensive",
      "oldest",
      "oncoming",
      "one-eyed",
      "one-year",
      "onstage",
      "onward",
      "opaque",
      "open-ended",
      "operating",
      "opportunist",
      "opposing",
      "opt-in",
      "ordinate",
      "outdone",
      "outlaw",
      "outsized",
      "overboard",
      "overheated",
      "oversize",
      "overworked",
      "oyster",
      "paced",
      "panting",
      "paralyzed",
      "paramount",
      "parental",
      "parted",
      "partisan",
      "passive",
      "pastel",
      "patriot",
      "peacekeeping",
      "pedestrian",
      "peevish",
      "penal",
      "penned",
      "pensive",
      "perceptual",
      "perky",
      "permissible",
      "pernicious",
      "perpetuate",
      "perplexed",
      "pervasive",
      "petrochemical",
      "philosophical",
      "picturesque",
      "pillaged",
      "piped",
      "piquant",
      "pitching",
      "plausible",
      "pliable",
      "plumb",
      "politician",
      "polygamous",
      "poorest",
      "portmanteau",
      "posed",
      "positive",
      "possible",
      "postpartum",
      "prank",
      "pre-emptive",
      "precocious",
      "predicted",
      "premium",
      "preparatory",
      "prerequisite",
      "prescient",
      "preserved",
      "presidential",
      "pressed",
      "pressurized",
      "presumed",
      "prewar",
      "priced",
      "pricier",
      "primal",
      "primer",
      "primetime",
      "printed",
      "private",
      "problem",
      "procedural",
      "process",
      "prodigious",
      "professional",
      "programmed",
      "progressive",
      "prolific",
      "promising",
      "promulgated",
      "pronged",
      "proportionate",
      "protracted",
      "pulled",
      "pulsed",
      "purgatory",
      "quick",
      "rapid-fire",
      "raunchy",
      "razed",
      "reactive",
      "readable",
      "realizing",
      "recognised",
      "recovering",
      "recurrent",
      "recycled",
      "redeemable",
      "reflecting",
      "regal",
      "registering",
      "reliable",
      "reminiscent",
      "remorseless",
      "removable",
      "renewable",
      "repeating",
      "repellent",
      "reserve",
      "resigned",
      "respectful",
      "rested",
      "restrict",
      "resultant",
      "retaliatory",
      "retiring",
      "revelatory",
      "reverend",
      "reversing",
      "revolving",
      "ridiculous",
      "right-hand",
      "ringed",
      "risque",
      "robust",
      "roomful",
      "rotating",
      "roused",
      "rubber",
      "run-down",
      "running",
      "runtime",
      "rustling",
      "safest",
      "salient",
      "sanctioned",
      "saute",
      "saved",
      "scandalized",
      "scarlet",
      "scattering",
      "sceptical",
      "scheming",
      "scoundrel",
      "scratched",
      "scratchy",
      "scrolled",
      "seated",
      "second-best",
      "segregated",
      "self-taught",
      "semiautomatic",
      "senior",
      "sensed",
      "sentient",
      "sexier",
      "shadowy",
      "shaken",
      "shaker",
      "shameless",
      "shaped",
      "shiny",
      "shipped",
      "shivering",
      "shoestring",
      "short",
      "short-lived",
      "signed",
      "simplest",
      "simplistic",
      "sizable",
      "skeleton",
      "skinny",
      "skirting",
      "skyrocketed",
      "slamming",
      "slanting",
      "slapstick",
      "sleek",
      "sleepless",
      "sleepy",
      "slender",
      "slimmer",
      "smacking",
      "smokeless",
      "smothered",
      "smouldering",
      "snuff",
      "socialized",
      "solid-state",
      "sometime",
      "sought",
      "spanking",
      "sparing",
      "spattered",
      "specialized",
      "specific",
      "speedy",
      "spherical",
      "spiky",
      "spineless",
      "sprung",
      "squint",
      "stainless",
      "standing",
      "starlight",
      "startled",
      "stately",
      "statewide",
      "stereoscopic",
      "sticky",
      "stimulant",
      "stinky",
      "stoked",
      "stolen",
      "storied",
      "strained",
      "strapping",
      "strengthened",
      "stubborn",
      "stylized",
      "suave",
      "subjective",
      "subjugated",
      "subordinate",
      "succeeding",
      "suffering",
      "summary",
      "sunset",
      "sunshine",
      "supernatural",
      "supervisory",
      "supply-side",
      "surrogate",
      "suspended",
      "suspenseful",
      "swarthy",
      "sweating",
      "sweeping",
      "swinging",
      "swooning",
      "sympathize",
      "synchronized",
      "synonymous",
      "synthetic",
      "tailed",
      "tallest",
      "tangible",
      "tanked",
      "tarry",
      "technical",
      "tectonic",
      "telepathic",
      "tenderest",
      "territorial",
      "testimonial",
      "theistic",
      "thicker",
      "threatening",
      "tight-lipped",
      "timed",
      "timely",
      "timid",
      "torrent",
      "totalled",
      "tougher",
      "traditional",
      "transformed",
      "trapped",
      "traveled",
      "traverse",
      "treated",
      "trial",
      "trunk",
      "trusting",
      "trying",
      "twisted",
      "two-lane",
      "tyrannical",
      "unaided",
      "unassisted",
      "unassuming",
      "unattractive",
      "uncapped",
      "uncomfortable",
      "uncontrolled",
      "uncooked",
      "uncooperative",
      "underground",
      "undersea",
      "undisturbed",
      "unearthly",
      "uneasy",
      "unequal",
      "unfazed",
      "unfinished",
      "unforeseen",
      "unforgivable",
      "unidentified",
      "unimaginative",
      "uninspired",
      "unintended",
      "uninvited",
      "universal",
      "unmasked",
      "unorthodox",
      "unparalleled",
      "unpleasant",
      "unprincipled",
      "unread",
      "unreasonable",
      "unregulated",
      "unreliable",
      "unremitting",
      "unsafe",
      "unsanitary",
      "unsealed",
      "unsuccessful",
      "unsupervised",
      "untimely",
      "unwary",
      "unwrapped",
      "uppity",
      "upstart",
      "useless",
      "utter",
      "valiant",
      "valid",
      "valued",
      "vanilla",
      "vaulting",
      "vaunted",
      "veering",
      "vegetative",
      "vented",
      "verbal",
      "verifying",
      "veritable",
      "versed",
      "vinyl",
      "virgin",
      "visceral",
      "visual",
      "voluptuous",
      "walk-on",
      "wanton",
      "warlike",
      "washed",
      "waterproof",
      "waved",
      "weakest",
      "well-bred",
      "well-chosen",
      "well-informed",
      "wetting",
      "wheeled",
      "whirlwind",
      "widen",
      "widening",
      "willful",
      "willing",
      "winnable",
      "winningest",
      "wireless",
      "wistful",
      "woeful",
      "wooded",
      "woodland",
      "wordless",
      "workable",
      "worldly",
      "worldwide",
      "worst-case",
      "worsted",
      "worthless"
];

let weirdWords = [
        "rural",
        "frugal",
        "twin",
        "santorum",
        "detritus",
        "entrepreneurial",
        "pronounciation",
        "moisture",
        "peculiarly",
        "crepuscular",
        "ubiquitous",
        "malarkey",
        "bubbles",
        "dude",
        "torque",
        "google",
        "visualization",
        "cliche",
        "floccinaucinihilipilification",
        "conundrums",
        "doodlesack",
        "volunteer",
        "mississippilessly",
        "calisthenics",
        "serendipity",
        "grommets",
        "dilettante",
        "macrosmatic",
        "supercalifragilisticexpialidocious",
        "flabergasted",
        "sphygmomanometer",
        "Kardashian",
        "hubbub",
        "prescription",
        "caulking",
        "wreath",
        "expat",
        "jentacular",
        "schnapps",
        "zdravstvuite",
        "phlegm",
        "specific",
        "quproch",
        "riboflavin",
        "cubersome",
        "garage",
        "flummoxed",
        "profiterole",
        "ruler",
        "dingleberry",
        "egg",
        "ombudsman",
        "perpendicular",
        "collate",
        "abruptly",
        "word",
        "bitter",
        "cellar",
        "airworthy",
        "stupendous",
        "swathe"
     ];

let zeldaWWCharacters = [
  "Abe",
        "Aryll",
        "Beedle",
        "Cyclos",
        "Daphnes Nohansen Hyrule",
        "Deities",
        "Doc Bandam",
        "Fado",
        "Fairy Queen",
        "Fishman",
        "Ganondorf",
        "Grandma",
        "Great Deku Tree",
        "Great Fairies",
        "Jabun",
        "Joel",
        "Killer Bees",
        "King of Red Lions",
        "Komali",
        "Laruto",
        "Lenzo",
        "Link",
        "Maggie and her father",
        "Makar",
        "Mesa",
        "Mila and her father",
        "Mrs. Marie",
        "Orca",
        "Quill",
        "Rito Chieftain",
        "Rose",
        "Sages",
        "Salvatore",
        "Sturgeon",
        "Sue-Belle",
        "Tetra",
        "The Pirates",
        "Tingle",
        "Tott",
        "Traveling Merchants",
        "Valoo",
        "Zelda",
        "Zephos",
        "Zill",
        "Zunari"
];

let tvShows = [
      "20/20",
      "21 Jump Street",
      "24",
      "2DTV",
      "30 Rock",
      "31 Minutes",
      "50 Cent: The Money and the Power",
      "50/50",
      "64 Zoo Lane",
      "6teen",
      "704 Hauser",
      "8 Simple Rules",
      "8th & Ocean",
      "A Class by Himself",
      "A Pup Named Scooby-Doo",
      "ANT Farm",
      "Access Hollywood",
      "According to Jim",
      "Ace Lightning",
      "Acme Hour",
      "Action",
      "Active Kids",
      "Adam's Rib",
      "Adventures in Paradise",
      "Airwolf",
      "Alcatraz",
      "Alfred J. Kwak",
      "Alias Smith and Jones",
      "Aliens in America",
      "All Is Forgiven",
      "Almost Human (TV series)",
      "Amazing Stories",
      "Amen",
      "America's Funniest Home Videos",
      "America's Funniest People",
      "American Chopper",
      "American Dragon: Jake Long",
      "American High",
      "American Pickers",
      "An Idiot Abroad",
      "Andromeda",
      "Andy Richter Controls the Universe",
      "Angel",
      "Anger Management",
      "Angry Beavers",
      "Animaniacs",
      "Animorphs",
      "Another World",
      "Any Dream Will Do",
      "Anything You Can Do",
      "Archie's Weird Mysteries",
      "Are You Smarter Than a 5th Grader?",
      "Ark II",
      "Arnie",
      "Arrow",
      "Arthur Godfrey and His Friends",
      "As Told By Ginger",
      "Australia's Next Top Model",
      "Awkward",
      "Baa Baa Black Sheep",
      "Babestation",
      "Baby Daddy",
      "Bachelor Father",
      "Bagpuss",
      "Banshee",
      "Barefoot in the Park",
      "Baretta",
      "Barnaby Jones",
      "Basil Brush",
      "Batfink",
      "Bayly (TV series)",
      "Baywatch Nights",
      "Beadle's About",
      "Beat The Chef",
      "Beating Heart",
      "Beetlejuice",
      "Behind the Music",
      "Being Human",
      "Belle and Sebastian (TV series)",
      "Bem-Vindos a Beirais",
      "Ben 10",
      "Ben 10: Ultimate Alien",
      "Benson",
      "Besame Tonto",
      "Beverly Hills, 90210",
      "Bewitched",
      "Big Arvo",
      "Big Town",
      "Billy",
      "Bionic Woman",
      "Birds of Prey",
      "Black Books",
      "Blake's 7",
      "Bless This House",
      "Blockbusters",
      "Blonde Charity Mafia",
      "Blue Heelers",
      "Blue Mountain State",
      "Blue Peter",
      "Boardwalk Empire",
      "Bob Hope Presents the Chrysler Theatre",
      "Bob Patterson",
      "BodyShaping",
      "Bones",
      "Boot Camp",
      "Borgia",
      "Boston Public",
      "Boy Meets World",
      "Branded",
      "Brat Camp",
      "Breaking Bad",
      "Breakout Kings",
      "Britain's Missing Top Model",
      "Brooke Knows Best",
      "Brotherly Love",
      "Brothers & Sisters",
      "Bubble Guppies",
      "Buck Rogers in the 25th Century",
      "Buck Rogers",
      "Bug Juice",
      "Bullseye",
      "Busting Loose",
      "C.O.P.S.",
      "C.P.O. Sharkey",
      "CI5: The New Professionals",
      "Cade's County",
      "Caesar's Hour",
      "Caillou",
      "Caitlin's Way",
      "Cake Boss",
      "Californication",
      "Camp Lazlo",
      "Camp Runamuck",
      "Camp",
      "Canadian Idol",
      "Cannon",
      "Cannonball",
      "Canterbury's Law",
      "Caprica",
      "Captain Caveman and the Teen Angels",
      "Captain Kangaroo",
      "Captain Planet and the Planeteers",
      "Captain Power",
      "Caribe",
      "Cash Cab",
      "CatDog",
      "Catalyst",
      "Catwalk",
      "Celebrity Rehab with Dr. Drew",
      "Centennial",
      "Chain Reaction",
      "ChalkZone",
      "Charlie Chalk",
      "Charlie Jade",
      "Charlie Rose",
      "Cheez TV",
      "Cheyenne",
      "Chicago Hope",
      "Child's Play",
      "China Beach",
      "Chopped",
      "Ciao Darwin",
      "City Lights",
      "Clangers",
      "Class of '74",
      "Clerks: The Animated Series",
      "Clone High",
      "Club Mario",
      "Clueless",
      "Co-Ed Fever",
      "Code Lyoko",
      "Codename: Kids Next Door",
      "Cold Case",
      "Cold Feet",
      "Colditz",
      "Columbo",
      "Commander in Chief",
      "Contraption",
      "Coronet Blue",
      "Cory in the House",
      "Cosmetic Surgery Live",
      "Countdown",
      "Country Style",
      "Countrytime (1960)",
      "Countrytime (1970)",
      "Cousin Skeeter",
      "Cover Up",
      "Cracking Up",
      "Criminal Minds",
      "Crossbow",
      "Crusade",
      "Cupcake Wars",
      "Curb Your Enthusiasm",
      "Da Ali G Show",
      "DaVinci's Inquest",
      "Dad's Army",
      "Damages",
      "Dan August",
      "Dance Academy",
      "Danger 5",
      "Danger Man",
      "Danny Phantom",
      "Darkwing Duck",
      "Dave Allen",
      "Dead of NIght",
      "Dear Sister",
      "Decisiones",
      "Demons",
      "Denkigai no Honya-san",
      "Desperate Housewives",
      "Dharma and Greg",
      "Dirty Sally",
      "Doctors (soap opera)",
      "Dog Bites Man",
      "Don't Forget Your Toothbrush",
      "Donny & Marie",
      "Doogie Howser, M.D.",
      "Double Trouble",
      "Dr. Finlay's Casebook",
      "Dr. Kildare",
      "Dr. Quinn, Medicine Woman",
      "Dragon Ball",
      "Duck Dynasty",
      "Due South",
      "E Street",
      "E/R",
      "ECW on Syfy",
      "ECW on TNN",
      "EZ Streets",
      "Earth 2",
      "Earth Revealed: Introductory Geology",
      "EastEnders",
      "Eastbound & Down",
      "Eastwick",
      "Ed, Edd, and Eddy",
      "Eddy Arnold Time",
      "Eerie, Indiana",
      "Eight is Enough",
      "Electra Woman and Dyna Girl",
      "Elementary",
      "Eleventh Hour",
      "Eli Stone",
      "Elizabeth R",
      "Emmerdale",
      "Engine Sentai Go-Onger",
      "Entourage",
      "Eric Sykes",
      "Eternal Law",
      "Eureka",
      "Everwood",
      "Extreme Dodgeball",
      "Extreme Makeover: Home Edition",
      "Eyewitness",
      "F Troop",
      "Falcon Crest",
      "Falling Skies",
      "Family Challenge",
      "Family Fortunes",
      "Family Guy",
      "Family Ties",
      "Family",
      "Farscape",
      "Fashion House",
      "Fast Money",
      "Fat Albert and the Cosby Kids",
      "Fat Guy Stuck in Internet",
      "Father Murphy",
      "Felicity",
      "Firefly",
      "Five Fingers",
      "Flamingo Road",
      "Flash Forward",
      "FlashForward",
      "Flashpoint",
      "Flavor Of Love",
      "Flight 29 Down",
      "Flight of the Conchords",
      "Flikken",
      "Flower Pot Men",
      "Flying Rhino Junior High",
      "Food Network Challenge",
      "Football Superstar",
      "Forgive or Forget",
      "Foster's Home for Imaginary Friends",
      "Fraggle Rock",
      "Franklin",
      "FreakyLinks",
      "Freewheelers",
      "Fresh Meat",
      "Friday Night Lights",
      "Fridays",
      "Friend or Foe?",
      "Friends",
      "Friendzone",
      "Fringe",
      "Frontier Justice",
      "Frontier",
      "Full House",
      "Futurama",
      "Future Weapons",
      "G-Saviour",
      "Gadget Boy & Heather",
      "Gal Circle",
      "Galactica 1980",
      "Gamezville",
      "Garfield and Friends",
      "Gargoyles",
      "General Hospital",
      "Gentle Touch",
      "George Lopez",
      "George Shrinks",
      "Get Smart",
      "Ghost Story",
      "Ghost Trackers",
      "Ghostwriter",
      "Gilligan's Island",
      "Glee",
      "Glenn Beck",
      "Going Places",
      "Gomer Pyle, U.S.M.C.",
      "Good Luck Charlie",
      "Good Morning, Mickey!",
      "Gravity Falls",
      "Grim & Evil",
      "Grim Adventures of Billy and Mandy",
      "Grimm",
      "Gunslinger Girl",
      "Half & Half",
      "Happy Endings",
      "Happy Tree Friends",
      "Hardcastle and McCormick",
      "Harper's Island",
      "Hart of Dixie",
      "Hart to Hart",
      "Harvey Birdman, Attorney at Law",
      "Have Gun - Will Travel",
      "Haven",
      "Hawaii Five-0",
      "Hawkins",
      "He-Man and the Masters of the Universe",
      "Hell's Kitchen (U.S. TV series)",
      "Here We Go Again",
      "Hergé's Adventures of Tintin",
      "Heston's Feasts",
      "Hey Vern, It's Ernest!",
      "Hi Hi Puffy AmiYumi",
      "Hitchhikers Guide To The Galaxy",
      "Hollywood Heights",
      "Home Improvement",
      "Hope & Faith",
      "Hot L Baltimore",
      "Hotel",
      "House of Cards",
      "House of Lies",
      "How It's Made",
      "Huff",
      "Human Target",
      "Hunter",
      "Hustle",
      "I Pity the Fool",
      "I'm In The Band",
      "In Living Color",
      "Inquizition",
      "Inspector Gadget",
      "Intervention",
      "Iron Chef America",
      "Iron Chef",
      "Ironside",
      "It Takes a Thief",
      "It's Garry Shandling's Show",
      "It's a Miracle",
      "Ivanhoe",
      "JONAS",
      "Jack of All Trades (TV series)",
      "Jackie Chan Adventures",
      "Jake and the Never Land Pirates",
      "Jason King",
      "Jem (TV series)",
      "Jep!",
      "Jeremiah",
      "Jersey Shore",
      "Jerseylicious",
      "Jimmy Kimmel Live!",
      "Joe Millionaire",
      "John Adams",
      "Johnny Bravo",
      "Joking Apart",
      "Josie and the Pussycats",
      "Jubilee USA",
      "Judge Joe Brown",
      "Juke Box Jury",
      "Juken Sentai Gekiranger",
      "Julia",
      "Julie",
      "Just Jordan",
      "Just Shoot Me!",
      "Justice League",
      "Kablam!",
      "Kaiketsu Zorro",
      "Kaiki Renai Sakusen",
      "Karen",
      "Kathy",
      "Keeping Up Appearances",
      "Keeping Up with the Kardashians",
      "Kenan & Kel",
      "Kickin' It",
      "Kids Incorporated",
      "Killer Instinct",
      "Kimba the White Lion",
      "Kitchen Confidential",
      "Knightmare",
      "Knowing Me, Knowing You",
      "Kolchak: The Night Stalker",
      "Kourtney and Khloé Take Miami",
      "Kraft Television Theatre",
      "Krypto the Superdog",
      "Kung Fu Panda",
      "Kyle XY",
      "L.A. Law",
      "Lab Rats",
      "Land of the Giants",
      "Land of the Lost",
      "Larry King Live",
      "Lassie",
      "Last Man Standing",
      "Late Night with Conan O'Brien",
      "Later with Bob Costas",
      "Law & Order: Trial by Jury",
      "Legend of the Seeker",
      "Lidsville",
      "Life Goes On",
      "Life Is Wild",
      "Life on Mars",
      "Life with Boys",
      "Life with Derek",
      "Life with Lucy",
      "Lifestyles of the Rich and Famous",
      "Lightning Point",
      "Lingo",
      "Little Einsteins",
      "Little People, Big World",
      "Live with Regis and Kathie Lee",
      "Live with Regis and Kelly",
      "Living Single",
      "Lizzie McGuire",
      "Location, Location, Location",
      "Loft Story",
      "Logan's Run",
      "Longstreet",
      "Lost",
      "Love & War",
      "Love Connection",
      "Love of Life",
      "Love, Sidney",
      "Lucky Louie",
      "Lunch with Soupy Sales",
      "MANswers",
      "Mad Men",
      "Made",
      "Maggie",
      "Make Room for Daddy",
      "Making Fiends",
      "Man About the House",
      "Man from Atlantis",
      "Man in a Suitcase",
      "Manhunt",
      "Manimal",
      "Mark Twain",
      "Married by America",
      "Marshall Law",
      "Martha Speaks",
      "Martial Law",
      "Martin Kane, Private Eye",
      "Mary Kay and Johnny",
      "Mary",
      "Masterpiece Theatre",
      "Maury",
      "Mayberry R.F.D.",
      "McCloud",
      "McHale's Navy",
      "McMorris & McMorris",
      "Me and My Monsters",
      "Meet Millie",
      "Meet the Browns",
      "Melody Rules",
      "Men Behaving Badly",
      "Men, Women & Dogs",
      "Metal Mickey",
      "Mickey Mouse Club",
      "Midnight Caller",
      "Mighty Max",
      "Mighty Morphin Power Rangers",
      "Ministry Of Mayhem",
      "Miss Fisher's Murder Mysteries",
      "Miss Marple",
      "Miss Match",
      "Mister Ed",
      "Mobile Suit Gundam 0083: Stardust Memory",
      "Monkey",
      "Monsters",
      "Moonlighting",
      "Mortal Kombat: Conquest",
      "Mr. & Mrs. Smith",
      "Mr. Adams and Eve",
      "Mr. Meaty",
      "Mr. Novak",
      "Mr. Peepers",
      "Mr. Sunshine",
      "Mr. Young",
      "Muktha",
      "Murder, She Wrote",
      "Must Love Kids",
      "Mutant X",
      "My Big Fat Obnoxious Boss",
      "My Boys",
      "My Family's Got GUTS",
      "My Favorite Martian",
      "My Kitchen Rules",
      "My Little Pony",
      "My Little Pony: Friendship Is Magic",
      "My Name Is Earl",
      "My Secret Identity",
      "My Wife and Kids",
      "My World and Welcome to It",
      "Mysterious Ways",
      "N.Y.P.D.",
      "NCIS",
      "NCIS: Los Angeles",
      "NYPD Blue",
      "Name That Tune",
      "National Bingo Night",
      "Ned and Stacey",
      "Needles and Pins",
      "Next",
      "Nine to Five",
      "North Shore",
      "Northern Exposure",
      "Not the Nine O'Clock News",
      "Nothing Sacred",
      "Noticentro 4",
      "Nowhere Man",
      "Number Please",
      "Nurse Jackie",
      "Nurses",
      "O2Be",
      "Ocean Girl",
      "Oddville, MTV",
      "Oggy and the Cockroaches",
      "Omnibus",
      "On the Rocks",
      "Once Upon a Time in Wonderland",
      "Once and Again",
      "One Day at a Time",
      "One Foot in the Grave",
      "One Tree Hill",
      "Online Nation",
      "Oobi",
      "Opposite Sex",
      "Our Friends in the North",
      "Our Miss Brooks",
      "Over There",
      "Ozark Jubilee",
      "Packed to the Rafters",
      "Pair of Kings",
      "Pan Am",
      "Panorama",
      "Parker Lewis Can't Lose",
      "Pass the Buck",
      "Password Plus",
      "Password",
      "Perfect Couples",
      "Perfect Hair Forever",
      "Pet Alien",
      "Peter Gunn",
      "Petticoat Junction",
      "Phil of the Future",
      "Pinky and the Brain",
      "Play the Percentages",
      "Please Don't Eat the Daisies",
      "Plonsters",
      "Pocoyo",
      "Pole Position (TV series)",
      "Police Ten 7",
      "Police Women of Maricopa County",
      "Politically Incorrect",
      "Pop! Goes the Country",
      "Pororo the Little Penguin",
      "Power Rangers Dino Thunder",
      "Power Rangers Jungle Fury",
      "Power Rangers Lost Galaxy",
      "Power Rangers Operation Overdrive",
      "Power Rangers S.P.D.",
      "Power Rangers Time Force",
      "Power Rangers in Space",
      "Prank Patrol",
      "Pranked",
      "Pretty Wild",
      "Prison Break",
      "Prisoners of Gravity",
      "Project G.e.e.K.e.R.",
      "Protagonistas De La Musica",
      "Puberty Blues",
      "Punk'd",
      "Punky Brewster",
      "Pushing Daisies",
      "Pussycat Dolls Present",
      "QI",
      "Quantum Leap",
      "Quatermass",
      "Que Locura",
      "Queen of Swords",
      "Queer Eye for the Straight Guy",
      "Quick Before They Catch Us",
      "Quintuplets",
      "Ramar of the Jungle",
      "Rawhide",
      "Real People",
      "Real Time with Bill Maher",
      "Real World/Road Rules Challenge",
      "Reaper",
      "Reba",
      "Rebelde Way",
      "Reborn!",
      "Rebound",
      "Red Dwarf",
      "Regular Show",
      "Relic Hunter",
      "Ren & Stimpy \"Adult Party Cartoon\"",
      "Rentaghost",
      "Rescue 8",
      "Return to Peyton Place",
      "Reunion",
      "Revenge",
      "Revolution",
      "Rhoda",
      "Riptide",
      "Rob & Big",
      "Rob Dyrdek's Fantasy Factory",
      "Robin Hood",
      "Rocket Robin Hood",
      "Roots: The Next Generations",
      "Ros na Rún",
      "Roseanne",
      "Route 66",
      "Rowan & Martin's Laugh-In",
      "Rubik the Amazing Cube",
      "Run Joe Run",
      "Run for Your Life",
      "Rurouni Kenshin",
      "Ryan",
      "Ryan's Hope",
      "S.W.A.T.",
      "SWAT Kats: The Radical Squadron",
      "Sabrina, The Animated Series",
      "Sadie J",
      "Sally",
      "Salute Your Shorts",
      "Sam",
      "Sanctuary",
      "Sanford and Son",
      "Saturday Night Live",
      "Saved by the Bell",
      "Saved by the Bell: The New Class",
      "Scandal",
      "Scarecrow and Mrs. King",
      "Scaredy Squirrel",
      "Schoolhouse Rock!",
      "Science Fiction Theatre",
      "Scooby-Doo, Where Are You!",
      "Scoop and Doozie",
      "Scrabble",
      "Sea Hunt",
      "SeaQuest DSV",
      "Secret Agent",
      "See It Now",
      "Seeing Things",
      "She-Ra: Princess of Power",
      "Sherlock",
      "Silver Spoons",
      "Simon & Simon",
      "Sing Along with Mitch",
      "Sir Francis Drake",
      "Sister, Sister",
      "Sisters",
      "Sleeper Cell",
      "So Little Time",
      "So Random",
      "Soap",
      "Sofia the First",
      "Solid Gold",
      "Something So Right",
      "Sonny with a Chance",
      "Sons of Anarchy",
      "South Park",
      "South of Nowhere",
      "Southland",
      "Space Patrol",
      "Space: 1999",
      "Spaced",
      "Spartakus and the Sun Beneath the Sea",
      "Speed Racer",
      "Spenser: For Hire",
      "Spider-Man: The New Animated Series",
      "SportsCenter",
      "Square Pegs",
      "St. Elsewhere",
      "Standoff",
      "Star Trek: Phase II",
      "Star Wars: Droids",
      "Stargate SG-1",
      "Starsky and Hutch",
      "Stingray",
      "Strangers with Candy",
      "Strike It Rich",
      "Strömsö",
      "Super Friends",
      "Super Greed",
      "Super Jeopardy!",
      "Supercar",
      "Supernatural",
      "Swamp Thing",
      "Switch",
      "T. J. Hooker",
      "TV Funhouse",
      "TV's Bloopers & Practical Jokes",
      "Take the High Road",
      "Takin' Over the Asylum",
      "TaleSpin",
      "Tallship Chronicles",
      "Team Umizoomi",
      "Teen Mom 2",
      "Teen Mom",
      "Teen Titans",
      "Terminator: The Sarah Connor Chronicles",
      "Terra Nova",
      "Terry and June",
      "Texaco Star Theater",
      "Texas Country Reporter",
      "That '80s Show",
      "That's My Mama",
      "That's the Question",
      "The 4400",
      "The Adventures of Jimmy Neutron: Boy Genius",
      "The Adventures of Pete & Pete",
      "The Adventures of Wild Bill Hickok",
      "The Adventures of William Tell",
      "The Alan Young Show",
      "The American Embassy",
      "The Avengers",
      "The Backyardigans",
      "The Barbara Stanwyck Show",
      "The Baron",
      "The Beachcombers",
      "The Benny Hill Show",
      "The Big Gig",
      "The Bionic Woman",
      "The Black Donnellys",
      "The Blacklist",
      "The Block",
      "The Bold and the Beautiful",
      "The Boondocks",
      "The Borgias",
      "The Brady Brides",
      "The Brothers",
      "The Bugaloos",
      "The Bugs Bunny Show",
      "The Buzz on Maggie",
      "The Cape",
      "The Carol Burnett Show",
      "The Catherine Tate Show",
      "The Celebrity Apprentice",
      "The Champions",
      "The Colbert Report",
      "The Colony",
      "The Cowboys",
      "The Crew",
      "The Crocodile Hunter",
      "The Curse of Oak Island",
      "The D.A.",
      "The Daily Show",
      "The Dr. Oz Show",
      "The Duck Factory",
      "The Dukes of Hazzard",
      "The Electric Company",
      "The Ellen DeGeneres Show",
      "The Ellen Show",
      "The Emperor's New School",
      "The Equalizer",
      "The F.B.I.",
      "The Face Is Familiar",
      "The Fast Show",
      "The Forgotten",
      "The Fosters",
      "The Four Just Men",
      "The Gene Autry Show",
      "The Generations Project",
      "The Ghost & Mrs. Muir",
      "The Good Guys",
      "The Governor and J.J.",
      "The Great Space Coaster",
      "The Heartland Series",
      "The Islanders",
      "The Jamie Foxx Show",
      "The Jay Leno Show",
      "The Jerry Springer Show",
      "The Jetsons",
      "The Jim Nabors Hour",
      "The Jimmy Dean Show",
      "The Joe Schmo Show",
      "The Joker's Wild",
      "The Kids in the Hall",
      "The Kids in the Hall: Death Comes to Town",
      "The King of Queens",
      "The League of Gentlemen",
      "The Letter People",
      "The Living Century",
      "The Lone Ranger",
      "The Loner",
      "The Loretta Young Show",
      "The Lost Room",
      "The Magic Hour",
      "The Magician",
      "The Magnificent Seven",
      "The Man Show",
      "The Man from U.N.C.L.E.",
      "The Mary Tyler Moore Hour",
      "The Merv Griffin Show",
      "The Middleman",
      "The Midnight Special",
      "The Mighty B!",
      "The Millionaire",
      "The Milton Berle Show",
      "The Mod Squad",
      "The Mole",
      "The Monroes",
      "The Munsters",
      "The Muppet Show",
      "The NBC Mystery Movie",
      "The New Adventures of Pinocchio",
      "The New Adventures of Zorro",
      "The New Dick Van Dyke Show",
      "The New Perry Mason",
      "The Newlywed Game",
      "The Nurses",
      "The O.C.",
      "The O'Reilly Factor",
      "The Odd Couple",
      "The Osbournes",
      "The PJs",
      "The Paradise",
      "The Parent 'Hood",
      "The Persuaders!",
      "The Phil Silvers Show",
      "The Price Is Right",
      "The Protectors",
      "The Psychiatrist",
      "The Quatermass Experiment",
      "The Rat Patrol",
      "The Real Adventures of Jonny Quest",
      "The Real Housewives of Beverly Hills",
      "The Real Housewives of D.C.",
      "The Rebel Billionaire: Branson's Quest for the Best",
      "The Ren & Stimpy Show",
      "The Restaurant",
      "The Restless Years",
      "The Rich List",
      "The Riches",
      "The Rifleman",
      "The Saddle Club",
      "The Sentimental Agent",
      "The Six Million Dollar Man",
      "The Smothers Brothers Comedy Hour",
      "The Spectacular Spider-Man",
      "The Sunday Comics",
      "The Super Mario Bros. Super Show!",
      "The Super",
      "The Surreal Life",
      "The Sword in the Stone",
      "The Tick",
      "The Tony Danza Show",
      "The Tortellis",
      "The Venture Bros.",
      "The Wallace and Ladmo Show",
      "The Walter Winchell Show",
      "The War at Home",
      "The Weakest Link",
      "The Wild Wild West",
      "The Wizard",
      "The Woodlanders",
      "The X Factor",
      "The Zoo Gang",
      "The_Librarians_(2014_TV_series)",
      "They Came from Outer Space",
      "Thicker than Water",
      "This Hour Has 22 Minutes",
      "Three Rivers",
      "Three's Company",
      "Threshold",
      "Thriller",
      "Thunderbirds",
      "Thundercats",
      "Tic-Tac-Dough",
      "Tim and Eric Nite Live!",
      "Tiny Toon Adventures",
      "Tiswas",
      "Titus",
      "Today on the Farm",
      "Today's Special",
      "Top Of The Pops",
      "Tosh.0",
      "Total Drama Action",
      "Total Drama: Revenge of the Island",
      "Totally Spies",
      "Touching Evil",
      "Tough Crowd with Colin Quinn",
      "Tour of Duty",
      "Tower Prep",
      "Trapper John, M.D.",
      "Trinity Blood",
      "Trivia Track",
      "TruTV Presents: World's Dumbest...",
      "True Blood",
      "True Jackson: VP",
      "Twenty One",
      "Twenty Questions",
      "Two Pints of Lager and a Packet of Crisps",
      "Two for the Money",
      "Ultimate Force",
      "Ultraman",
      "Ulysses 31",
      "Under the Dome",
      "United States of Tara",
      "Until Tomorrow",
      "Utopia",
      "V",
      "V: The Final Battle",
      "Van Der Valk",
      "Veep",
      "Veronica Mars",
      "Victorious",
      "Vikings",
      "Voltron: Defender of the Universe",
      "Walker, Texas Ranger",
      "Wanted: Dead or Alive",
      "Warehouse 13",
      "Wayside",
      "Webster",
      "Weeds",
      "West Point Story",
      "Whammy! The All-New Press Your Luck",
      "What the Papers Say",
      "What's Happening!!",
      "Whatever Happened to Robot Jones?",
      "Wheel of Fortune 2000",
      "Wheel of Fortune",
      "When Games Attack",
      "Whiplash",
      "Who Wants to Be a Millionaire?",
      "Who Wants to Be a Superhero?",
      "Who Wants to Marry My Dad?",
      "Who's the Boss?",
      "Wife Swap",
      "Wild On!",
      "Win, Lose or Draw",
      "Winning Streak",
      "Wire in the Blood",
      "With This Ring",
      "Wizards of Waverly Place",
      "Women's Murder Club",
      "Wonder Showzen",
      "Wonderfalls",
      "Workaholics",
      "Working Girl",
      "World Blackjack Tour",
      "World's Most Amazing Videos",
      "World's Wildest Police Videos",
      "Yancy Derringer",
      "Yes Minister",
      "Yin Yang Yo!",
      "Yogi's Gang",
      "You Asked For It",
      "You Bet Your Life",
      "You Can't Do That on Television",
      "Your Hit Parade",
      "Yu-Gi-Oh! 5D's",
      "Yu-Gi-Oh! Arc V",
      "Yu-Gi-Oh! GX",
      "ZOOM",
      "Zoids",
      "Zoobilee Zoo",
      "Zooboomafoo",
      "Zorro and Son",
      "Zorro",
      "Zorro: Generation Z",
      "Zorro: La Espada y la Rosa",
      "Zumbo",
      "'Allo 'Allo!",
      "'Til Death",
      "Óli á Hrauni"
    ];

//all words curtersy of corpora.
//i just needed random words, let's hope I have enough. 

$(document).ready(setup);

function setup() {

}
